# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'second.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 600)
        MainWindow.setMinimumSize(QtCore.QSize(450, 450))
        MainWindow.setMaximumWidth((650))
        MainWindow.setStyleSheet("""#MainWindow{background: rgba(0, 0, 0, 50);}""")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet(
            "QFrame{color: white;}\n"
            "QLabel{color: white;}\n"
            "QPushButton{color: white;}\n"
            "\n"
            "QScrollArea{background: transparent; border-radius: 4px;}\n"
            "QScrollBar:vertical{\n"
            "background: transparent;\n"
            "width: 7px;\n"
            "border-radius: 10px;}\n"
            "QScrollBar::handle{background:  rgba(0, 0, 0, 140); border-radius: 10px;}\n"
            "QScrollBar::handle::hover {background:  rgba(0, 0, 0, 180); border-radius: 10px;}\n"
            "QScrollBar::handle:vertical {width: 25px; min-height: 10px;}\n"
            ""
        )
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.background_frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.background_frame.setFont(font)
        self.background_frame.setStyleSheet(
            "QFrame#background_frame{background: rgba(0, 0, 0, 50); border-radius: 4px; }"
        )
        self.background_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.background_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.background_frame.setObjectName("background_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.background_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_frame = QtWidgets.QFrame(self.background_frame)
        self.top_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.top_frame.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.top_frame.setFont(font)
        self.top_frame.setStyleSheet(
            "QFrame#top_frame{background: rgba(0, 0, 0, 100); border-radius: 4px; }"
        )
        self.top_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_frame.setObjectName("top_frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.top_frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.top_frame)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.frame_4.setFont(font)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.add_show_pushButton = QtWidgets.QPushButton(self.frame_4)
        self.add_show_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.add_show_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.add_show_pushButton.setFont(font)
        self.add_show_pushButton.setStyleSheet(
            "QPushButton{background: seagreen; \n"
            "border-radius: 4px; \n"
            "image: url('/icons/add.png')}\n"
            "QPushButton::hover{\n"
            "background: mediumseagreen; \n"
            "border-radius: 4px; }\n"
            ""
        )
        self.add_show_pushButton.setText("")
        self.add_show_pushButton.setObjectName("add_show_pushButton")
        self.horizontalLayout_3.addWidget(self.add_show_pushButton)
        self.horizontalLayout.addWidget(self.frame_4, 0, QtCore.Qt.AlignLeft)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.frame_3.setFont(font)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimize_pushButton = QtWidgets.QPushButton(self.frame_3)
        self.minimize_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.minimize_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.minimize_pushButton.setFont(font)
        self.minimize_pushButton.setStyleSheet(
            "QPushButton{background: teal; \n"
            "border-radius: 4px; \n"
            "image: url('/icons/minimize.png')}\n"
            "QPushButton::hover{\n"
            "background: cornflowerblue; \n"
            "border-radius: 4px; \n"
            "}"
        )
        self.minimize_pushButton.setText("")
        self.minimize_pushButton.setObjectName("minimize_pushButton")
        self.horizontalLayout_2.addWidget(
            self.minimize_pushButton, 0, QtCore.Qt.AlignRight
        )
        self.close_pushButton = QtWidgets.QPushButton(self.frame_3)
        self.close_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.close_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.close_pushButton.setFont(font)
        self.close_pushButton.setStyleSheet(
            "QPushButton{background: tomato; \n"
            "border-radius: 4px;\n"
            "image: url('/icons/close.png')\n"
            "}\n"
            "QPushButton::hover{background: orangered; \n"
            "border-radius: 4px;}"
        )
        self.close_pushButton.setText("")
        self.close_pushButton.setObjectName("close_pushButton")
        self.horizontalLayout_2.addWidget(
            self.close_pushButton, 0, QtCore.Qt.AlignRight
        )
        self.horizontalLayout.addWidget(self.frame_3, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_3.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.top_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.link_lineEdit = QtWidgets.QLineEdit(self.frame_2)
        self.link_lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.link_lineEdit.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(10)
        self.link_lineEdit.setFont(font)
        self.link_lineEdit.setStyleSheet(
            "background: white;\n"
            "border: 1px solid lightgrey; \n"
            "border-radius: 4px;\n"
            "color: black; \n"
            "padding-left: 4px;"
        )
        self.link_lineEdit.setObjectName("link_lineEdit")
        self.horizontalLayout_4.addWidget(self.link_lineEdit)
        self.add_pushButton = QtWidgets.QPushButton(self.frame_2)
        self.add_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.add_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.add_pushButton.setFont(font)
        self.add_pushButton.setStyleSheet(
            "QPushButton{background: seagreen; \n"
            "border-radius: 4px; \n"
            "image: url('/icons/add.png')}\n"
            "QPushButton::hover{\n"
            "background: mediumseagreen; \n"
            "border-radius: 4px; }\n"
            ""
        )
        self.add_pushButton.setText("")
        self.add_pushButton.setObjectName("add_pushButton")
        self.horizontalLayout_4.addWidget(self.add_pushButton)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.top_frame)
        self.notification_frame = QtWidgets.QFrame(self.background_frame)
        self.notification_frame.setMinimumSize(QtCore.QSize(0, 30))
        self.notification_frame.setMaximumSize(QtCore.QSize(16777215, 30))
        self.notification_frame.setStyleSheet(
            "border-radius: 4px; background: seagreen; "
        )
        self.notification_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.notification_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.notification_frame.setObjectName("notification_frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.notification_frame)
        self.verticalLayout_6.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.notification_label = QtWidgets.QLabel(self.notification_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.notification_label.setFont(font)
        self.notification_label.setAlignment(QtCore.Qt.AlignCenter)
        self.notification_label.setObjectName("notification_label")
        self.verticalLayout_6.addWidget(self.notification_label)
        self.verticalLayout.addWidget(self.notification_frame)
        self.middle_frame = QtWidgets.QFrame(self.background_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.middle_frame.setFont(font)
        self.middle_frame.setStyleSheet("")
        self.middle_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.middle_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.middle_frame.setObjectName("middle_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.middle_frame)
        self.verticalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(self.middle_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.scrollArea.setFont(font)
        self.scrollArea.setStyleSheet(
            "QFrame{background: transparent; border-radius: 4px;}\n"
            "QLabel{background: transparent; border-radius: 4px;}\n"
            "QPushButton{background: transparent; border-radius: 4px;}\n"
            "QWidget{background: transparent; border-radius: 4px;}\n"
            "\n"
            "\n"
            "\n"
            "\n"
            ""
        )
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setSizeAdjustPolicy(
            QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow
        )
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 505, 525))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.scroll_frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.scroll_frame.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.scroll_frame.setFont(font)
        self.scroll_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.scroll_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.scroll_frame.setObjectName("scroll_frame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scroll_frame)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_5.addWidget(self.scroll_frame, 0, QtCore.Qt.AlignTop)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea)
        self.verticalLayout.addWidget(self.middle_frame)
        self.bottom_frame = QtWidgets.QFrame(self.background_frame)
        self.bottom_frame.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        self.bottom_frame.setFont(font)
        self.bottom_frame.setStyleSheet(
            "QFrame#bottom_frame{background: rgba(0, 0, 0, 100); border-radius: 4px; }"
        )
        self.bottom_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame.setObjectName("bottom_frame")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.bottom_frame)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, -1)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.bottom_frame_left = QtWidgets.QFrame(self.bottom_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        self.bottom_frame_left.setFont(font)
        self.bottom_frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame_left.setObjectName("bottom_frame_left")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.bottom_frame_left)
        self.verticalLayout_12.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.title_label = QtWidgets.QLabel(self.bottom_frame_left)
        self.title_label.setMinimumSize(QtCore.QSize(300, 0))
        self.title_label.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.verticalLayout_12.addWidget(self.title_label)
        self.bottom_frame_left_middle = QtWidgets.QFrame(self.bottom_frame_left)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        self.bottom_frame_left_middle.setFont(font)
        self.bottom_frame_left_middle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame_left_middle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame_left_middle.setObjectName("bottom_frame_left_middle")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.bottom_frame_left_middle)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.artist_label = QtWidgets.QLabel(self.bottom_frame_left_middle)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(9)
        font.setItalic(True)
        self.artist_label.setFont(font)
        self.artist_label.setObjectName("artist_label")
        self.horizontalLayout_13.addWidget(self.artist_label)
        self.duration_label = QtWidgets.QLabel(self.bottom_frame_left_middle)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        self.duration_label.setFont(font)
        self.duration_label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter
        )
        self.duration_label.setObjectName("duration_label")
        self.horizontalLayout_13.addWidget(self.duration_label, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_12.addWidget(self.bottom_frame_left_middle)
        self.duration_progress_frame = QtWidgets.QFrame(self.bottom_frame_left)
        self.duration_progress_frame.setMaximumSize(QtCore.QSize(16777215, 5))
        self.duration_progress_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.duration_progress_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.duration_progress_frame.setObjectName("duration_progress_frame")
        self.verticalLayout_12.addWidget(self.duration_progress_frame)
        self.duration_progressBar = QtWidgets.QProgressBar(self.bottom_frame_left)
        self.duration_progressBar.setMaximumSize(QtCore.QSize(16777215, 5))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.duration_progressBar.setFont(font)
        self.duration_progressBar.setStyleSheet(
            "border-radius: 4px; background: transparent; color: transparent;"
        )
        self.duration_progressBar.setProperty("value", 30)
        self.duration_progressBar.setTextVisible(False)
        self.duration_progressBar.setObjectName("duration_progressBar")
        self.verticalLayout_12.addWidget(self.duration_progressBar)
        self.horizontalLayout_11.addWidget(self.bottom_frame_left)
        self.bottom_frame_right = QtWidgets.QFrame(self.bottom_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        self.bottom_frame_right.setFont(font)
        self.bottom_frame_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame_right.setObjectName("bottom_frame_right")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.bottom_frame_right)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.bottom_frame_right_top = QtWidgets.QFrame(self.bottom_frame_right)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        self.bottom_frame_right_top.setFont(font)
        self.bottom_frame_right_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame_right_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame_right_top.setObjectName("bottom_frame_right_top")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.bottom_frame_right_top)
        self.verticalLayout_11.setContentsMargins(0, -1, -1, 0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.show_pushButton = QtWidgets.QPushButton(self.bottom_frame_right_top)
        self.show_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.show_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.show_pushButton.setSizeIncrement(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.show_pushButton.setFont(font)
        self.show_pushButton.setStyleSheet(
            "QPushButton{background: transparent;\n" "image: url('/icons/up.png');}"
        )
        self.show_pushButton.setText("")
        self.show_pushButton.setObjectName("show_pushButton")
        self.verticalLayout_11.addWidget(self.show_pushButton)
        self.verticalLayout_10.addWidget(
            self.bottom_frame_right_top, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignTop
        )
        self.bottom_frame_right_bottom = QtWidgets.QFrame(self.bottom_frame_right)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        self.bottom_frame_right_bottom.setFont(font)
        self.bottom_frame_right_bottom.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottom_frame_right_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_frame_right_bottom.setObjectName("bottom_frame_right_bottom")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.bottom_frame_right_bottom)
        self.horizontalLayout_12.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.prev_pushButton = QtWidgets.QPushButton(self.bottom_frame_right_bottom)
        self.prev_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.prev_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.prev_pushButton.setSizeIncrement(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.prev_pushButton.setFont(font)
        self.prev_pushButton.setStyleSheet(
            "QPushButton{background: transparent;\n" "image: url('/icons/prev.png');}"
        )
        self.prev_pushButton.setText("")
        self.prev_pushButton.setObjectName("prev_pushButton")
        self.horizontalLayout_12.addWidget(self.prev_pushButton)
        self.play_pushButton = QtWidgets.QPushButton(self.bottom_frame_right_bottom)
        self.play_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.play_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.play_pushButton.setSizeIncrement(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.play_pushButton.setFont(font)
        self.play_pushButton.setStyleSheet(
            "QPushButton{background: transparent;\n" "image: url('/icons/pause.png');}"
        )
        self.play_pushButton.setText("")
        self.play_pushButton.setObjectName("play_pushButton")
        self.horizontalLayout_12.addWidget(self.play_pushButton)
        self.next_pushButton = QtWidgets.QPushButton(self.bottom_frame_right_bottom)
        self.next_pushButton.setMinimumSize(QtCore.QSize(30, 30))
        self.next_pushButton.setMaximumSize(QtCore.QSize(30, 30))
        self.next_pushButton.setSizeIncrement(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Variable Static Text")
        font.setPointSize(11)
        self.next_pushButton.setFont(font)
        self.next_pushButton.setStyleSheet(
            "QPushButton{background: transparent;\n" "image: url('/icons/next.png');}"
        )
        self.next_pushButton.setText("")
        self.next_pushButton.setObjectName("next_pushButton")
        self.horizontalLayout_12.addWidget(self.next_pushButton)
        self.verticalLayout_10.addWidget(
            self.bottom_frame_right_bottom, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignTop
        )
        self.horizontalLayout_11.addWidget(self.bottom_frame_right)
        self.verticalLayout.addWidget(self.bottom_frame)
        self.verticalLayout_2.addWidget(self.background_frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setMaximumSize(QtCore.QSize(16777215, 1))
        self.statusBar.setStyleSheet("background: rgba(0, 0, 0, 50); ")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Youtube App"))
        self.notification_label.setText(
            _translate("MainWindow", "The track has been downloaded")
        )
        self.title_label.setText(_translate("MainWindow", "Title"))
        self.artist_label.setText(_translate("MainWindow", "Artist"))
        self.duration_label.setText(_translate("MainWindow", "Duration"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
