# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fourth_draft.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1252, 696)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.main_label = QtWidgets.QLabel(self.centralwidget)
        self.main_label.setMinimumSize(QtCore.QSize(1000, 600))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.main_label.setFont(font)
        self.main_label.setAlignment(QtCore.Qt.AlignCenter)
        self.main_label.setObjectName("main_label")
        self.gridLayout.addWidget(self.main_label, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.crypto_label = QtWidgets.QLabel(self.centralwidget)
        self.crypto_label.setMaximumSize(QtCore.QSize(250, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.crypto_label.setFont(font)
        self.crypto_label.setObjectName("crypto_label")
        self.verticalLayout_2.addWidget(self.crypto_label)
        self.crypto_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.crypto_comboBox.setMaximumSize(QtCore.QSize(250, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.crypto_comboBox.setFont(font)
        self.crypto_comboBox.setObjectName("crypto_comboBox")
        self.verticalLayout_2.addWidget(self.crypto_comboBox)
        self.training_label = QtWidgets.QLabel(self.centralwidget)
        self.training_label.setMaximumSize(QtCore.QSize(250, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.training_label.setFont(font)
        self.training_label.setObjectName("training_label")
        self.verticalLayout_2.addWidget(self.training_label)
        self.training_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.training_comboBox.setMaximumSize(QtCore.QSize(250, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.training_comboBox.setFont(font)
        self.training_comboBox.setObjectName("training_comboBox")
        self.verticalLayout_2.addWidget(self.training_comboBox)
        self.predicted_label = QtWidgets.QLabel(self.centralwidget)
        self.predicted_label.setMaximumSize(QtCore.QSize(250, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.predicted_label.setFont(font)
        self.predicted_label.setObjectName("predicted_label")
        self.verticalLayout_2.addWidget(self.predicted_label)
        self.predicted_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.predicted_comboBox.setMaximumSize(QtCore.QSize(250, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.predicted_comboBox.setFont(font)
        self.predicted_comboBox.setObjectName("predicted_comboBox")
        self.verticalLayout_2.addWidget(self.predicted_comboBox)
        self.currency_label = QtWidgets.QLabel(self.centralwidget)
        self.currency_label.setMaximumSize(QtCore.QSize(250, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.currency_label.setFont(font)
        self.currency_label.setObjectName("currency_label")
        self.verticalLayout_2.addWidget(self.currency_label)
        self.currency_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.currency_comboBox.setMaximumSize(QtCore.QSize(250, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.currency_comboBox.setFont(font)
        self.currency_comboBox.setObjectName("currency_comboBox")
        self.verticalLayout_2.addWidget(self.currency_comboBox)
        self.predict_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.predict_pushButton.setMaximumSize(QtCore.QSize(250, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.predict_pushButton.setFont(font)
        self.predict_pushButton.setObjectName("predict_pushButton")
        self.verticalLayout_2.addWidget(self.predict_pushButton)
        self.analyze_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.analyze_pushButton.setMaximumSize(QtCore.QSize(250, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.analyze_pushButton.setFont(font)
        self.analyze_pushButton.setObjectName("analyze_pushButton")
        self.verticalLayout_2.addWidget(self.analyze_pushButton)

        self.plot_pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.plot_pushButton.setMaximumSize(QtCore.QSize(250, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plot_pushButton.setFont(font)
        self.plot_pushButton.setObjectName("plot_pushButton")
        self.verticalLayout_2.addWidget(self.plot_pushButton)

        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.sub_label = QtWidgets.QLabel(self.centralwidget)
        self.sub_label.setMaximumSize(QtCore.QSize(16777215, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sub_label.setFont(font)
        self.sub_label.setText("")
        self.sub_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sub_label.setObjectName("sub_label")
        self.gridLayout.addWidget(self.sub_label, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1252, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Crypto Currency Predictor"))
        self.main_label.setText(_translate(
            "MainWindow", "Welcome to Crypto Currency Predictor"))
        self.crypto_label.setText(_translate(
            "MainWindow", "Select Crypto Currency:"))
        self.training_label.setText(_translate(
            "MainWindow", "Select Training Data Length:"))
        self.predicted_label.setText(_translate(
            "MainWindow", "Select Predicted Data Length:"))
        self.currency_label.setText(
            _translate("MainWindow", "Select Currency:"))
        self.predict_pushButton.setText(_translate("MainWindow", "Predict"))
        self.analyze_pushButton.setText(
            _translate("MainWindow", "Analyze Correlation"))
        self.plot_pushButton.setText(_translate("MainWindow", "Plot Prices"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
